let
    Source = Csv.Document(File.Contents("S:\InfoCore\Aplicaciones\Modelos Información\Retornos\Revision retornos diarios1.csv"),[Delimiter=",", Columns=28, Encoding=1252, QuoteStyle=QuoteStyle.None]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}, {"Column10", type text}, {"Column11", type text}, {"Column12", type text}, {"Column13", type text}, {"Column14", type text}, {"Column15", type text}, {"Column16", type text}, {"Column17", type text}, {"Column18", type text}, {"Column19", type text}, {"Column20", type text}, {"Column21", type text}, {"Column22", type text}, {"Column23", type text}, {"Column24", type text}, {"Column25", type text}, {"Column26", type text}, {"Column27", type text}, {"Column28", type text}}),
    #"Removed Top Rows" = Table.Skip(#"Changed Type",5),
    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Top Rows", [PromoteAllScalars=true]),
    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Account", type text}, {"Security", type text}, {"CUSIP", type text}, {"FLAR Rating", type text}, {"FLAR Sector", type text}, {"Issuer", type text}, {"ISIN", type text}, {"Group", type text}, {"Class", type text}, {"Beg Curr Face (000)", type number}, {"Local Beg Ttl Accrued", type number}, {"Local Beg Security Market Value", type number}, {"Local Beg Ttl Market Value", type number}, {"End Currt Face (000)", type number}, {"Local Beg Market Price", type number}, {"Local End Market Price", type number}, {"Local End Total Accrued", type number}, {"Local End Security Market Value", type number}, {"Begin Coupon Rate", type number}, {"End Coupon Rate", type number}, {"Int. Freq.", Int64.Type}, {"Local End Total Market Value", type number}, {"Daily Total TWRR Tot. Contr", type number}, {"Daily Total TWRR", type number}, {"Prin. Currency", type text}, {"Description", type text}, {"Amort. Meth.", type text}, {"Last Pricing Date", type date}}),
    #"Filtered Rows" = Table.SelectRows(#"Changed Type1", each [#"Beg Curr Face (000)"] <> 0 or [#"End Currt Face (000)"] <> 0)
in
    #"Filtered Rows"
